### ISSUE TITLE
Did you rebase pull request #2 instead of merging?

### ISSUE THREAD

**Issue by ghost** [anusaini/shelp#3]
Did you rebase pull request #2 ?

```
my-fork/master is at a85fa7f Closes #1 - touch files before sourcing.
your-fork/master is at ba1926b Closes #1 - touch files before sourcing.
```

**Comment by anusaini** [comment]
Yes. You should raise request from topic/feature branch.

**Comment by ghost** [comment]
Hmm, I rebase while pulling changes from remote. I have never seen this feature on github. I saw that I am author but the hash has changed. Took me a minute to understand that it was a rebase / cherry-pick.

Thanks for suggestion.
